### ISSUE TITLE
关于State的疑问

### ISSUE THREAD

**Issue by YouheiLee** [compose-museum/hello-compose#214]
在某位贡献者的博客中看到一个例子，我自己动手试了一下，得到了一个令我费解的结果。想咨询下大佬

下面的代码比较符合我的预期结果，随着点击button，text进行了改变并且Foo并没有进行重组

```
@SuppressLint("UnrememberedMutableState")
@Composable
fun Foo() {
    val textState by TestHolder.textState
    Log.e("Compose", "Foo")

    Button(onClick = {
        TestHolder.update("$textState $textState")
    }.also { Log.e("Compose", "Button") }) {
        Log.e("Compose", "Button content lambda")
        Text(textState).also { Log.e("Compose", "Text") }
    }
}

object TestHolder {
    val textState: MutableState<String> = mutableStateOf("1")

    fun update(text: String) {
        textState.value = text
    }
}
```

但有意思的是，如果我这样写，text改变的时候，Foo就会重组

```
@SuppressLint("UnrememberedMutableState")
@Composable
fun Foo() {
    val textState by TestHolder.textState
    Log.e("Compose", "Foo")
    Bar(text = textState)
}

object TestHolder {
    val textState: MutableState<String> = mutableStateOf("1")

    fun update(text: String) {
        textState.value = text
    }
}

@Composable
fun Bar(text: String) {
    Button(onClick = {
        TestHolder.update("$text $text")
    }.also { Log.e("Compose", "Button") }) {
        Log.e("Compose", "Button content lambda")
        Text(text).also { Log.e("Compose", "Text") }
    }
}
```

这是为什么呢？看了一些资料，仍然没有搞明白

**Comment by YouheiLee** [comment]
哦我搞明白了，是这样的，正如博客中所讲到的同text改变时不只输出了"Text"，也输出了"Button content lambda"一样的原因，如果是采用第二种写法的话，compose会认为在Foo中也使用到了TestHolder.textState，而在第一种写法中，compose不认为在Foo中使用到了TestHolder.textState。更直观的理解这个问题的方式是，只需要在第一种写法中加一行代码，就会产生和第二种写法一样的结果。如下:

```
@SuppressLint("UnrememberedMutableState")
@Composable
fun Foo() {
    val textState by TestHolder.textState
    Log.e("Compose", "Foo")

    // 只需要加这么一行，甚至接下来的代码都没有用到text，但compose仍然会认为Foo中需要响应TestHolder.textState的变化
    val text = textState

    Button(onClick = {
        TestHolder.update("$textState $textState")
    }.also { Log.e("Compose", "Button") }) {
        Log.e("Compose", "Button content lambda")
        Text(textState).also { Log.e("Compose", "Text") }
    }
}

object TestHolder {
    val textState: MutableState<String> = mutableStateOf("1")

    fun update(text: String) {
        textState.value = text
    }
}
```

**Comment by Nthily** [comment]
> 哦我搞明白了，是这样的，正如博客中所讲到的同text改变时不只输出了"Text"，也输出了"Button content lambda"一样的原因，如果是采用第二种写法的话，compose会认为在Foo中也使用到了TestHolder.textState，而在第一种写法中，compose不认为在Foo中使用到了TestHolder.textState。更直观的理解这个问题的方式是，只需要在第一种写法中加一行代码，就会产生和第二种写法一样的结果。如下:
> 
> ```
> @SuppressLint("UnrememberedMutableState")
> @Composable
> fun Foo() {
>     val textState by TestHolder.textState
>     Log.e("Compose", "Foo")
> 
>     // 只需要加这么一行，甚至接下来的代码都没有用到text，但compose仍然会认为Foo中需要响应TestHolder.textState的变化
>     val text = textState
> 
>     Button(onClick = {
>         TestHolder.update("$textState $textState")
>     }.also { Log.e("Compose", "Button") }) {
>         Log.e("Compose", "Button content lambda")
>         Text(textState).also { Log.e("Compose", "Text") }
>     }
> }
> 
> object TestHolder {
>     val textState: MutableState<String> = mutableStateOf("1")
> 
>     fun update(text: String) {
>         textState.value = text
>     }
> }
> ```

是的，因为在这种情况下，Compose 的最小重组作用域是 `Foo()` 了，因为 `val text = textState` 这句读取了一个 State，为此当 `textState` 改变了， `Foo()` 也会随之重组

**Comment by YouheiLee** [comment]
感谢回复和知识分享。
不过我仍有一些问题想请教，正如我上面说到的，我在尝试理解State，但是感觉有点难以理解，像我下面这个使用VerticalPager的例子，就更让我困惑了，能帮我看看吗？

```
@ExperimentalPagerApi
@Composable
fun Pager(workList: List<Work> = listOf()) {
    val pagerState = rememberPagerState(
        pageCount = workList.size,
        initialOffscreenLimit = 2
    )

    Log.e("Compose", "Pager re-compose, count: $workList.size")

    VerticalPager(state = pagerState) { page ->
        workList.getOrNull(page)?.let { work ->
            WorkItem(page = page, work = work)
        }
    }
}
```
如果在另一个composable的function中使用Pager并且传入workList的话，那么在workList数据变化的时候, Pager会引起两次重组，例如第一次传入空数组[]，第二次传入数据[work1, work2]，那么可以看到三次输出，分别是
1. "Pager re-compose, count: 0"
2. "Pager re-compose, count: 2"
3. "Pager re-compose, count: 2"

测试后发现问题在于这个rememberPagerState, 于是将代码改成了下面这样子

```
@ExperimentalPagerApi
@Composable
fun Pager2(workList: List<Work> = listOf()) {

    val pagerState = rememberSaveable(saver = PagerState.Saver) {
        PagerState(pageCount = workList.size, offscreenLimit = 2)
    }
    pagerState.pageCount = workList.size

    Log.e("Compose", "Pager re-compose, count: $workList.size")

    Text(
        text = pagerState.pageCount.toString(),
        fontSize = 50f.sp,
        color = Color.White
    )
}
```
测试输出结果，Pager和Pager2输出结果一致，都输出了三次，即在更新列表之后，又一次重复的重组。正常我理解应该只有两次输出:
1. "Pager re-compose, count: 0"
2. "Pager re-compose, count: 2"

问题在这行代码: 
```
pagerState.pageCount = workList.size
```
这行代码改变了state，从而导致Pager2又做了一次重组，但是内容中又需要用到这个state，究竟要怎么处理才能去掉这个多余的重组呢？

**Comment by RugerMcCarthy** [comment]
![image](https://user-images.githubusercontent.com/30253468/133612544-7f3ce523-0824-4182-9a69-a2e96bbe21e5.png)
通过源码可知，直接使用rememberPagerState和分别使用rememberSaveable再进行pagerState.pageCount = workList.size的行为是一样的。然而我没有出现复现会出现重复recompose的case，方便的话能否提供一个简单的复现示例

**Comment by YouheiLee** [comment]
不能复现吗？我这个环境下是必现的
```
accompanist_version = "0.18.0"
compose_version = "1.0.2"
hilt_version = "2.37"
```

```
@ExperimentalPagerApi
@ExperimentalAnimationApi
@ExperimentalCoilApi
@ExperimentalMaterialApi
@Composable
fun AppEntry(host: ComponentActivity) {
    val testVM: TestViewModel = hiltViewModel(host)
    val testState by testVM.uiState
    ScreenTest(testState = testState)
}

data class TestState(
    val workList: List<String> = emptyList()
)

@HiltViewModel
class TestViewModel @Inject constructor() : ViewModel() {

    companion object {
        private const val PAGE_REQUEST_COUNT = 20
        private const val REQUEST_MIN_OFFSET = 3
    }

    private var fetchDataJob: Job? = null

    private val _uiState = mutableStateOf(TestState())
    val uiState: State<TestState> = _uiState

    init {
        fetchDataList()
    }

    private fun fetchDataList() {
        val curState = uiState.value
        if (fetchDataJob?.isActive == true) {
            return
        }
        fetchDataJob = viewModelScope.launch {
            withContext(Dispatchers.IO) {
                delay(100)
            }
            _uiState.value = curState.copy(
                workList = listOf("page1", "page2")
            )
        }
    }
}

@ExperimentalCoilApi
@ExperimentalMaterialApi
@ExperimentalPagerApi
@Composable
fun ScreenTest(testState: TestState) {
    Box(Modifier.fillMaxSize()) {
        PagerTest(workList = testState.workList)
    }
}

@ExperimentalPagerApi
@Composable
fun PagerTest(workList: List<String> = emptyList()) {
    val pagerState = rememberPagerState(
        pageCount = workList.size,
        initialOffscreenLimit = 2
    )

    Log.e("Compose", "Pager re-compose, size: ${workList.size}")

    VerticalPager(state = pagerState) { page ->
        workList.getOrNull(page)?.let { work ->
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Text(text = work)
            }
        }
    }
}
```

**Comment by RugerMcCarthy** [comment]
这是个好问题，通过排查问题原因如下：
![image](https://user-images.githubusercontent.com/30253468/133711706-da85bf60-80f4-4be3-9e0b-65331c53e9d1.png)
当TestState更新时会触发第一次recompose，这是预期的。当调用至PagerTest中的pagerState.pageCount = workList.size时，会调用pageCount的setter，通过上图可以看到在setter中进行了读行为，这导致了当前composable被添加至pageCount这个mutableState观察者列表中，后面验证通过时真正赋值时遍会触发当前composable再次recompose（也就是第二次recompose），那为什么没有第三第四次呢，这是因为第二次recompose时数值没有发生更新。为了验证这个问题，我写了一个小示例复现这个问题。
var _pageCount by mutableStateOf(0)
var pageCount: Int
    get() = _pageCount
    set(value) {
        if (value != _pageCount) {
            _pageCount = value
        }
    }
@ExperimentalPagerApi
@Composable
fun PagerTest(workList: List<String> = emptyList()) {
    pageCount = workList.size
    Log.e("Compose", "Pager re-compose, size: ${workList.size}")
}
上面这个示例会复现你所述的问题，既然知道了问题该如何解决呢？

这个问题在于setter里进行了读行为，导致了当前composable被监听，而我们在写时并不希望被监听。为了解决这个问题，我们可以考虑将写行为异步执行，这样即可避免了当前composable被监听。因为异步执行时对应的是GlobalSnapshot，而GlobalSnapshot的读观察者为空，所以不会导致composable被监听。具体内容可以参考我的文章：https://juejin.cn/post/6974974061466091556#heading-4

**Comment by RugerMcCarthy** [comment]
问题解决方案可以参考如下：
@ExperimentalPagerApi
@Composable
fun PagerTest(workList: List<String> = emptyList()) {
    val pagerState = rememberSaveable(saver = PagerState.Saver) {
        PagerState(pageCount = workList.size, offscreenLimit = 2)
    }
    LaunchedEffect(workList.size) {
        pagerState.pageCount = workList.size
    }
    Log.e("Compose", "Pager re-compose, size: ${workList.size}")
}

**Comment by YouheiLee** [comment]
哦原来劳模就是说的你啊

**Comment by RugerMcCarthy** [comment]
刚去看了下accompanist 0.18.1-SNAPSHOT最新版本，问题已经被修复了～

**Comment by YouheiLee** [comment]
> 刚去看了下accompanist 0.18.1-SNAPSHOT最新版本，问题已经被修复了～

试了一下snapshot确实没问题了，有意思，不过发现Compose也不好写啊，一不小心就掉坑里了
