### ISSUE TITLE
如果我想提供样例App我该如何去做

### ISSUE THREAD

**Issue by SakurajimaMaii** [compose-museum/hello-compose#228]

**Comment by Nthily** [comment]
Hi ！提供样例 App 的话，最好可以写出来具体完成步骤的文档，可以参考[这个](https://docs.compose.net.cn/open-source-project/compose-douban/)

然后你可以在 [mkdocs.yml](https://github.com/compose-museum/hello-compose/blob/main/mkdocs.yml#L104) 这里添加你的 `.md` 文件

本地测试的办法在[这里](https://github.com/compose-museum/hello-compose#%E5%85%B3%E4%BA%8E%E8%B4%A1%E7%8C%AE)

测试完就可以直接提交 PR 啦
