### ISSUE TITLE
什么情况下,使用remember带参数的用法?

### ISSUE THREAD

**Issue by Stars-One** [compose-museum/hello-compose#250]
如题,一般使用`remember`关键字都是没有带参数,但我看文档时候**发现`remember`可以带参数**,看说明不是很明白

带参数的用法是应该在什么情况下使用?有明白的大佬可以举个栗子说明不?

```
@Composable
inline fun <T : Any?> remember(key1: Any?, calculation: (@DisallowComposableCalls () -> T)?): T
```

> Remember the value returned by calculation if key1 is equal to the previous composition, otherwise produce and remember a new value by calling calculation.

文档地址: [androidx.compose.runtime  |  Android Developers](https://developer.android.google.cn/reference/kotlin/androidx/compose/runtime/package-summary#remember)

**Comment by Stars-One** [comment]
实际上,我自己测试,发现`remember`好像本身就实现了你所说的那个情况:

> 只有当值发生了真正变化才去重新计算应该记住的值

```
MaterialTheme() {
    val person = remember {
        mutableStateOf(Person("张三", 18))
    }
    var mycount by remember("1"){
        mutableStateOf(12)
    }.also {  Log.e("--tttt remember",it.value.toString()) }

    Column {
        Text("现在数据: ${mycount}").also {
            Log.e("--tttt",mycount.toString())
        }
        repeat(2) {
            Button(onClick = {
                mycount = it
            }) {
                Text(text = "数值改为改为${it}")
            }
        }
   }
}
```

有两个按钮,可以把数值改为0或1,我点了两下改为0的那个按钮的话,就是只会第一次触发打印,第二次就没有触发打印了,**如果加了key的话,key设置为0,然后也是一样的效果**

**Comment by Nthily** [comment]
可能我说的不够具体，你可以这样理解
```
remember { x }，表示只有当 x 变化，就重新记住 x
remember(y) { x }，表示只有当 y 变化，就重新记住 x
```

<img width="471" alt="%$%O2{(G~X}NF@}5 `KHHIS" src="https://user-images.githubusercontent.com/31311826/140175780-72a3e869-dca9-40f3-ad43-ce4945ee7db3.png">

这样应该更容易理解一些

**Comment by Stars-One** [comment]
ok 大致明白了
