### ISSUE TITLE
我用 compose navhost 做导航，返回时页面会重建，请问怎么解决？

### ISSUE THREAD

**Issue by zqlq4ever** [compose-museum/hello-compose#252]
![image](https://user-images.githubusercontent.com/37474811/141254005-b9400271-a96b-46d3-9882-8ed58806b710.png)
使用 navhost ，实现类似多 fragment 效果，从 A 打开 B，再返回 A ，A 会重建，列表数据重新刷新，输入框内容也会置空，而不是进入前的状态，请问怎样实现类似 activity 的那种页面返回。

**Comment by Nthily** [comment]
使用 navigation 会导致 Composable 重组的，如果你使用 `viewModel` 来存储界面的状态需要保证 `viewModel` 是单例

**Comment by zqlq4ever** [comment]
好的，知道了，谢谢
